window.titleLibrary = [
  {
    title: "我试了 7 天 AI 自动化，真正省时间的是这 3 个流程",
    platform: "xiaohongshu",
    category: "ai",
    pattern: "实验天数 + 真实发现 + 数字清单",
    hook: "用亲测感降低怀疑，用数字承诺信息密度。",
    signals: ["AI", "自动化", "7 天", "3 个", "省时间"],
  },
  {
    title: "不是你不会用 ChatGPT，是你一直在问错问题",
    platform: "xiaohongshu",
    category: "ai",
    pattern: "不是 X，而是 Y",
    hook: "把用户失败原因从能力转向方法，减少防御感。",
    signals: ["ChatGPT", "不是", "问错", "问题"],
  },
  {
    title: "AI 写的网站跑不起来？先检查这 5 个地方",
    platform: "xiaohongshu",
    category: "ai",
    pattern: "痛点提问 + 检查清单",
    hook: "把抽象焦虑变成可执行排查步骤。",
    signals: ["AI", "网站", "跑不起来", "5 个", "检查"],
  },
  {
    title: "普通人做副业，最怕的不是没时间",
    platform: "wechat",
    category: "side",
    pattern: "人群 + 反常识判断",
    hook: "用反常识观点拉开阅读入口。",
    signals: ["普通人", "副业", "不是", "没时间"],
  },
  {
    title: "普通人第一份副业，不要从最难的技能开始",
    platform: "xiaohongshu",
    category: "side",
    pattern: "人群阶段 + 阻断建议",
    hook: "降低进入门槛，直接命中新手启动焦虑。",
    signals: ["普通人", "第一份", "副业", "不要", "技能"],
  },
  {
    title: "副业迟迟没开始，往往卡在这 3 个假问题",
    platform: "xiaohongshu",
    category: "side",
    pattern: "进度痛点 + 数字根因",
    hook: "把拖延解释成问题识别错误，适合引出方法。",
    signals: ["副业", "没开始", "3 个", "假问题"],
  },
  {
    title: "接单 3 个月后，我发现低价客户最贵",
    platform: "wechat",
    category: "side",
    pattern: "经历周期 + 反差结论",
    hook: "经历感和利益冲突同时出现，适合深度内容。",
    signals: ["接单", "3 个月", "发现", "低价", "客户"],
  },
  {
    title: "想靠副业赚钱，先别急着学技能",
    platform: "douyin",
    category: "side",
    pattern: "愿望 + 阻断建议",
    hook: "先否定常见动作，再引出更关键动作。",
    signals: ["副业", "赚钱", "先别", "技能"],
  },
  {
    title: "小红书标题没点击？多数人卡在第一句话",
    platform: "xiaohongshu",
    category: "content",
    pattern: "平台痛点 + 多数人误区",
    hook: "点名平台和具体问题，适合精准用户。",
    signals: ["小红书", "标题", "点击", "多数人"],
  },
  {
    title: "我把 100 条爆款标题拆完，发现都在用这 4 个钩子",
    platform: "bilibili",
    category: "content",
    pattern: "大样本拆解 + 发现 + 数字钩子",
    hook: "用样本量制造可信度，用钩子承诺方法论。",
    signals: ["100 条", "爆款标题", "拆", "4 个", "钩子"],
  },
  {
    title: "别再追热点了，账号起不来通常是选题太散",
    platform: "wechat",
    category: "content",
    pattern: "阻断动作 + 根因判断",
    hook: "帮创作者从表面动作回到结构问题。",
    signals: ["热点", "账号", "选题", "太散"],
  },
  {
    title: "打工人想提高效率，先删掉这 3 类待办",
    platform: "xiaohongshu",
    category: "career",
    pattern: "人群 + 目标 + 反向动作",
    hook: "不是增加方法，而是删除负担，信息更有新鲜感。",
    signals: ["打工人", "效率", "3 类", "待办"],
  },
  {
    title: "面试总被刷？可能不是简历不够漂亮",
    platform: "douyin",
    category: "career",
    pattern: "痛点提问 + 反常识解释",
    hook: "把失败原因从表象挪到更深层。",
    signals: ["面试", "简历", "不是", "漂亮"],
  },
  {
    title: "我见过最稳的职场成长，不靠加班",
    platform: "wechat",
    category: "career",
    pattern: "强判断 + 否定常见路径",
    hook: "用稳定性和非加班制造吸引力。",
    signals: ["职场", "成长", "不靠", "加班"],
  },
  {
    title: "焦虑的时候，别急着做计划",
    platform: "xiaohongshu",
    category: "growth",
    pattern: "情绪场景 + 阻断建议",
    hook: "贴近状态，再给出反直觉动作。",
    signals: ["焦虑", "别急", "计划"],
  },
  {
    title: "自律失败很多次后，我换了一个更轻的方法",
    platform: "xiaohongshu",
    category: "growth",
    pattern: "失败经历 + 方法转向",
    hook: "承认失败，降低距离感，再给替代方案。",
    signals: ["自律", "失败", "方法"],
  },
  {
    title: "真正拉开差距的，不是每天多努力一点",
    platform: "wechat",
    category: "growth",
    pattern: "大判断 + 反常识",
    hook: "适合展开观点，吸引读者找答案。",
    signals: ["真正", "差距", "不是", "努力"],
  },
  {
    title: "客户嫌贵时，不要马上降价",
    platform: "xiaohongshu",
    category: "product",
    pattern: "销售场景 + 阻断动作",
    hook: "对应高频商业场景，给出关键行为提醒。",
    signals: ["客户", "嫌贵", "不要", "降价"],
  },
  {
    title: "一个报价单，暴露了你的服务值不值钱",
    platform: "wechat",
    category: "product",
    pattern: "具体物件 + 价值判断",
    hook: "用小切口承载商业判断。",
    signals: ["报价单", "服务", "值钱"],
  },
  {
    title: "产品卖不动，先看这 4 个转化断点",
    platform: "douyin",
    category: "product",
    pattern: "结果痛点 + 数字排查",
    hook: "把销售问题拆成可诊断节点。",
    signals: ["产品", "卖不动", "4 个", "转化"],
  },
  {
    title: "This one prompt fixed my messy content workflow",
    platform: "x",
    category: "ai",
    pattern: "结果 + 具体对象",
    hook: "一句话给出前后变化，适合短平台。",
    signals: ["prompt", "content", "workflow", "fixed"],
  },
  {
    title: "Your title is not boring. It is trying to do too many jobs.",
    platform: "x",
    category: "content",
    pattern: "重新定义问题",
    hook: "用一句判断替用户命名问题。",
    signals: ["title", "boring", "too many jobs"],
  },
  {
    title: "I stopped selling hours and started selling outcomes",
    platform: "x",
    category: "side",
    pattern: "过去动作 + 新动作",
    hook: "直接呈现定位升级。",
    signals: ["selling", "hours", "outcomes"],
  },
  {
    title: "从 0 做账号，最容易浪费时间的是这一步",
    platform: "bilibili",
    category: "content",
    pattern: "阶段 + 最大坑",
    hook: "新手会天然代入，想知道是哪一步。",
    signals: ["从 0", "账号", "浪费时间", "一步"],
  },
  {
    title: "我用一个表格，把副业想法筛掉了一半",
    platform: "bilibili",
    category: "side",
    pattern: "工具 + 明确结果",
    hook: "用低门槛工具制造可复制感。",
    signals: ["表格", "副业", "筛掉", "一半"],
  },
  {
    title: "AI 工具越多，越要先固定自己的工作流",
    platform: "wechat",
    category: "ai",
    pattern: "趋势 + 反向建议",
    hook: "不是推荐更多工具，而是强调系统。",
    signals: ["AI 工具", "工作流", "越多"],
  },
  {
    title: "别让自动化变成新的手工活",
    platform: "wechat",
    category: "ai",
    pattern: "短句警告",
    hook: "一句话刺中错误使用自动化的痛点。",
    signals: ["自动化", "手工活"],
  },
  {
    title: "这 5 个提示词习惯，比收藏 100 个模板更重要",
    platform: "xiaohongshu",
    category: "ai",
    pattern: "数字清单 + 对比",
    hook: "用对比提升价值判断。",
    signals: ["5 个", "提示词", "100 个", "模板"],
  },
  {
    title: "内容做不下去，往往不是因为你懒",
    platform: "xiaohongshu",
    category: "content",
    pattern: "痛点 + 非责备解释",
    hook: "减少羞耻感，让用户愿意继续看。",
    signals: ["内容", "做不下去", "不是", "懒"],
  },
  {
    title: "选题库不是越多越好，而是越能决策越好",
    platform: "wechat",
    category: "content",
    pattern: "不是 X，而是 Y",
    hook: "从数量指标转向决策质量。",
    signals: ["选题库", "不是", "越多", "决策"],
  },
  {
    title: "一条视频没人看，可能标题已经输了一半",
    platform: "douyin",
    category: "content",
    pattern: "结果痛点 + 提前失败点",
    hook: "指出流量失败的前置原因。",
    signals: ["视频", "没人看", "标题", "输"],
  },
  {
    title: "你不是没有执行力，是目标太难被开始",
    platform: "xiaohongshu",
    category: "growth",
    pattern: "不是 X，而是 Y",
    hook: "替用户卸下自责，同时给结构解释。",
    signals: ["执行力", "目标", "开始"],
  },
  {
    title: "30 岁以后，我更相信低摩擦成长",
    platform: "wechat",
    category: "growth",
    pattern: "年龄阶段 + 新观点",
    hook: "用人生阶段触发认同。",
    signals: ["30 岁", "成长", "低摩擦"],
  },
  {
    title: "效率工具换了一堆，真正有用的是这张表",
    platform: "bilibili",
    category: "growth",
    pattern: "失败对比 + 具体工具",
    hook: "从泛工具回到一个可复制方案。",
    signals: ["效率工具", "有用", "表"],
  },
  {
    title: "简历改了 10 版，还是没有面试？先看岗位匹配",
    platform: "xiaohongshu",
    category: "career",
    pattern: "努力无效 + 根因提示",
    hook: "承认努力，再指出更关键变量。",
    signals: ["简历", "10 版", "面试", "岗位匹配"],
  },
  {
    title: "职场沟通的关键，不是把话说漂亮",
    platform: "wechat",
    category: "career",
    pattern: "领域 + 反常识",
    hook: "打开更深层的沟通标准。",
    signals: ["职场沟通", "不是", "漂亮"],
  },
  {
    title: "老板真正想看的，不是你的工作量",
    platform: "douyin",
    category: "career",
    pattern: "对象 + 反常识",
    hook: "直接点名职场权力关系和评价标准。",
    signals: ["老板", "不是", "工作量"],
  },
  {
    title: "服务卖不上价，通常是交付边界太模糊",
    platform: "wechat",
    category: "product",
    pattern: "商业结果 + 根因判断",
    hook: "把价格问题转成服务设计问题。",
    signals: ["服务", "卖不上价", "交付边界"],
  },
  {
    title: "客户不是不想买，是还没看见确定性",
    platform: "xiaohongshu",
    category: "product",
    pattern: "不是 X，而是 Y",
    hook: "把成交问题从意愿转到信任建设。",
    signals: ["客户", "不是", "买", "确定性"],
  },
];
